### PR TITLE
Update for PEP A

### PR DESCRIPTION
**Pull request by encukou**
My suggestions, in the form of a pull request :)

### CODE REVIEW

**Comment by torsava** [comment]
> .. with one of the valid suffixes (e.g. `.py`, `.pyc`, ..., `.so`).  The suffixes are tried in order.

It might be confusing that the order in the parens does not correspond to the actual order.

**Comment by torsava** [comment]
> This mechanism also solves the minor issue of importing a module from `site-packages` that shadows a standard library module.

site-packages modules can't shadow stdlib, as they are below them (on sys.path).

**Comment by torsava** [comment]
> While we strongly recommend that these files only raise an `ImportError` with an appropriate message, there is no reason to limit customization options—**especially since importing a Python module is trivial to implement.**

What do you mean by the last part?

**Comment by torsava** [comment]
And lastly, the original python-dev discussion is now not mentioned. I suppose we can mention it in the Abstract?

**Comment by torsava** [comment]
Python 3.6 introduces a `ModuleNotFoundError`, I reckon we should suggest using that instead of the standard `ImportError`.

https://docs.python.org/3.6/library/exceptions.html#ModuleNotFoundError

**Comment by encukou** [comment]
A new commit is here. Hopefully this addresses all your comments.
The missing link to python-dev discussion was an editing mistake on my part.

**Comment by torsava** [comment]
A few typos: https://github.com/encukou/pep-drafts/pull/2

**Comment by torsava** [comment]
The changes are great! The only thing I'm still not certain on is what do you mean by this part?

> While we strongly recommend that these files only raise `ModuleNotFoundError` with an appropriate message, there is no reason to limit customization options—**especially since importing a Python module with an additional suffix is, implementation-wise, a small change in importlib.**

**Comment by encukou** [comment]
What I'm trying to say (in a few words) is that the code change is done at a point where the import machinery already, in the common case, imports a module. Adding ".missing.py" to the list of suffixes and handling it by SourceFileLoader is a small change – it's more like a configuration change than implementing new functionality. Compared to our earlier ideas like only putting the ImportError message (or some part of it) in the file, this approach is both more flexible and much easier to implement.

**Comment by encukou** [comment]
Do you have any suggestion for a better wording? If not, we can leave that part out.

**Comment by torsava** [comment]
Ah I see. Honestly I would omit it, we already mentioned the simplicity of the implementation above, and I don't think it's truly pertinent to this point.

**Comment by encukou** [comment]
OK, omitted. Can we merge it in this form?

**Comment by torsava** [comment]
Absolutely.

That means we're missing only the Abstract and the text draft should be complete. I'll try to write it by tomorrow.

**Pull request merged**
